#!/bin/sh

cat <<EOF > /usr/share/nginx/html/env-injector.js
window.__ENV__ = {
  TOOL_PGADMIN4_PORT: "${TOOL_PGADMIN4_PORT}",
  TOOL_REDISCOMMANDER_PORT: "${TOOL_REDISCOMMANDER_PORT}",
  FINANCE_FIREFLYCORE_PORT: "${FINANCE_FIREFLYCORE_PORT}",
  FINANCE_FIREFLYIMPORT_PORT: "${FINANCE_FIREFLYIMPORT_PORT}",
  ORGANIZATION_VIKUNJA_PORT: "${ORGANIZATION_VIKUNJA_PORT}",
  INVENTORY_HOMEBOX_PORT: "${INVENTORY_HOMEBOX_PORT}",
  DASHBOARD_HOMEHUB_PORT: "${DASHBOARD_HOMEHUB_PORT}",
  DIGITAL_STIRLINGPDF_PORT: "${DIGITAL_STIRLINGPDF_PORT}",
  DIGITAL_PAPERLESS_PORT: "${DIGITAL_PAPERLESS_PORT}",
  FOOD_MEALIE_PORT: "${FOOD_MEALIE_PORT}",
  FOOD_GROCY_PORT: "${FOOD_GROCY_PORT}",
  SECURITY_VAULTWARDEN_PORT: "${SECURITY_VAULTWARDEN_PORT}",
  COLLECTION_KOILLECTION_PORT: "${COLLECTION_KOILLECTION_PORT}",
  TOOL_GRAFANA_PORT: "${TOOL_GRAFANA_PORT}"
};
EOF

exec "$@"
