#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_FIREFLY_III_USER} WITH PASSWORD '${POSTGRES_FIREFLY_III_PASSWORD}';
	CREATE DATABASE ${POSTGRES_FIREFLY_III_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_FIREFLY_III_DB} TO ${POSTGRES_FIREFLY_III_USER};
    ALTER DATABASE ${POSTGRES_FIREFLY_III_DB} OWNER TO ${POSTGRES_FIREFLY_III_USER};    

    CREATE USER ${POSTGRES_AUTHENTIK_USER} WITH PASSWORD '${POSTGRES_AUTHENTIK_PASSWORD}';
    CREATE DATABASE ${POSTGRES_AUTHENTIK_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_AUTHENTIK_DB} TO ${POSTGRES_AUTHENTIK_USER};
    ALTER DATABASE ${POSTGRES_AUTHENTIK_DB} OWNER TO ${POSTGRES_AUTHENTIK_USER};
EOSQL