#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_FIREFLY_III_USER} WITH PASSWORD '${POSTGRES_FIREFLY_III_PASSWORD}';
	CREATE DATABASE ${POSTGRES_FIREFLY_III_DB};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_FIREFLY_III_DB} TO ${POSTGRES_FIREFLY_III_USER};
    ALTER DATABASE ${POSTGRES_FIREFLY_III_DB} OWNER TO ${POSTGRES_FIREFLY_III_USER};

    CREATE USER ${POSTGRES_VIKUNJA_USER} WITH PASSWORD '${POSTGRES_VIKUNJA_PASSWORD}';
    CREATE DATABASE ${POSTGRES_VIKUNJA_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_VIKUNJA_DB} TO ${POSTGRES_VIKUNJA_USER};
    ALTER DATABASE ${POSTGRES_VIKUNJA_DB} OWNER TO ${POSTGRES_VIKUNJA_USER};

    CREATE USER ${POSTGRES_HOMEBOX_USER} WITH PASSWORD '${POSTGRES_HOMEBOX_PASSWORD}';
    CREATE DATABASE ${POSTGRES_HOMEBOX_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_HOMEBOX_DB} TO ${POSTGRES_HOMEBOX_USER};
    ALTER DATABASE ${POSTGRES_HOMEBOX_DB} OWNER TO ${POSTGRES_HOMEBOX_USER};

    CREATE USER ${POSTGRES_STIRLING_USER} WITH PASSWORD '${POSTGRES_STIRLING_PASSWORD}';
    CREATE DATABASE ${POSTGRES_STIRLING_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_STIRLING_DB} TO ${POSTGRES_STIRLING_USER};
    ALTER DATABASE ${POSTGRES_STIRLING_DB} OWNER TO ${POSTGRES_STIRLING_USER};

    CREATE USER ${POSTGRES_PAPERLESS_USER} WITH PASSWORD '${POSTGRES_PAPERLESS_PASSWORD}';
    CREATE DATABASE ${POSTGRES_PAPERLESS_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_PAPERLESS_DB} TO ${POSTGRES_PAPERLESS_USER};
    ALTER DATABASE ${POSTGRES_PAPERLESS_DB} OWNER TO ${POSTGRES_PAPERLESS_USER};

    CREATE USER ${POSTGRES_MEALIE_USER} WITH PASSWORD '${POSTGRES_MEALIE_PASSWORD}';
    CREATE DATABASE ${POSTGRES_MEALIE_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_MEALIE_DB} TO ${POSTGRES_MEALIE_USER};
    ALTER DATABASE ${POSTGRES_MEALIE_DB} OWNER TO ${POSTGRES_MEALIE_USER};

    CREATE USER ${POSTGRES_VAULTWARDEN_USER} WITH PASSWORD '${POSTGRES_VAULTWARDEN_PASSWORD}';
    CREATE DATABASE ${POSTGRES_VAULTWARDEN_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_VAULTWARDEN_DB} TO ${POSTGRES_VAULTWARDEN_USER};
    ALTER DATABASE ${POSTGRES_VAULTWARDEN_DB} OWNER TO ${POSTGRES_VAULTWARDEN_USER};

    CREATE USER ${POSTGRES_KOILLECTION_USER} WITH PASSWORD '${POSTGRES_KOILLECTION_PASSWORD}';
    CREATE DATABASE ${POSTGRES_KOILLECTION_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_KOILLECTION_DB} TO ${POSTGRES_KOILLECTION_USER};
    ALTER DATABASE ${POSTGRES_KOILLECTION_DB} OWNER TO ${POSTGRES_KOILLECTION_USER};
EOSQL