export type RuntimeEnv = {
  TOOL_PGADMIN4_PORT?: string;
  TOOL_REDISCOMMANDER_PORT?: string;
  FINANCE_FIREFLYCORE_PORT?: string;
  FINANCE_FIREFLYIMPORT_PORT?: string;
  ORGANIZATION_VIKUNJA_PORT?: string;
  INVENTORY_HOMEBOX_PORT?: string;
  DASHBOARD_HOMEHUB_PORT?: string;
  DIGITAL_STIRLINGPDF_PORT?: string;
  DIGITAL_PAPERLESS_PORT?: string;
  FOOD_MEALIE_PORT?: string;
  FOOD_GROCY_PORT?: string;
  SECURITY_VAULTWARDEN_PORT?: string;
  COLLECTION_KOILLECTION_PORT?: string;
  TOOL_GRAFANA_PORT?: string;
}

export const env: RuntimeEnv = import.meta.env.DEV ? {
  TOOL_PGADMIN4_PORT: import.meta.env.VITE_TOOL_PGADMIN4_PORT,
  TOOL_REDISCOMMANDER_PORT: import.meta.env.VITE_TOOL_REDISCOMMANDER_PORT,
  FINANCE_FIREFLYCORE_PORT: import.meta.env.VITE_FINANCE_FIREFLYCORE_PORT,
  FINANCE_FIREFLYIMPORT_PORT: import.meta.env.VITE_FINANCE_FIREFLYIMPORT_PORT,
  DIGITAL_STIRLINGPDF_PORT: import.meta.env.VITE_DIGITAL_STIRLINGPDF_PORT,
  DIGITAL_PAPERLESS_PORT: import.meta.env.VITE_DIGITAL_PAPERLESS_PORT,
  ORGANIZATION_VIKUNJA_PORT: import.meta.env.VITE_ORGANIZATION_VIKUNJA_PORT,
  INVENTORY_HOMEBOX_PORT: import.meta.env.VITE_INVENTORY_HOMEBOX_PORT,
  FOOD_GROCY_PORT: import.meta.env.VITE_FOOD_GROCY_PORT,
  FOOD_MEALIE_PORT: import.meta.env.VITE_FOOD_MEALIE_PORT,
  SECURITY_VAULTWARDEN_PORT: import.meta.env.VITE_SECURITY_VAULTWARDEN_PORT,
  DASHBOARD_HOMEHUB_PORT: import.meta.env.VITE_DASHBOARD_HOMEHUB_PORT,
  COLLECTION_KOILLECTION_PORT: import.meta.env.VITE_COLLECTION_KOILLECTION_PORT,
  TOOL_GRAFANA_PORT: import.meta.env.VITE_TOOL_GRAFANA_PORT
} : {
  TOOL_PGADMIN4_PORT: window.__ENV__?.TOOL_PGADMIN4_PORT ?? '',
  TOOL_REDISCOMMANDER_PORT: window.__ENV__?.TOOL_REDISCOMMANDER_PORT ?? '',
  FINANCE_FIREFLYCORE_PORT: window.__ENV__?.FINANCE_FIREFLYCORE_PORT ?? '',
  FINANCE_FIREFLYIMPORT_PORT: window.__ENV__?.FINANCE_FIREFLYIMPORT_PORT ?? '',
  DIGITAL_STIRLINGPDF_PORT: window.__ENV__?.DIGITAL_STIRLINGPDF_PORT ?? '',
  DIGITAL_PAPERLESS_PORT: window.__ENV__?.DIGITAL_PAPERLESS_PORT ?? '',
  ORGANIZATION_VIKUNJA_PORT: window.__ENV__?.ORGANIZATION_VIKUNJA_PORT ?? '',
  INVENTORY_HOMEBOX_PORT: window.__ENV__?.INVENTORY_HOMEBOX_PORT ?? '',
  FOOD_GROCY_PORT: window.__ENV__?.FOOD_GROCY_PORT ?? '',
  FOOD_MEALIE_PORT: window.__ENV__?.FOOD_MEALIE_PORT ?? '',
  SECURITY_VAULTWARDEN_PORT: window.__ENV__?.SECURITY_VAULTWARDEN_PORT ?? '',
  DASHBOARD_HOMEHUB_PORT: window.__ENV__?.DASHBOARD_HOMEHUB_PORT ?? '',
  COLLECTION_KOILLECTION_PORT: window.__ENV__?.COLLECTION_KOILLECTION_PORT ?? '',
  TOOL_GRAFANA_PORT: window.__ENV__?.TOOL_GRAFANA_PORT ?? ''
};